Repository googleapis/nodejs-firestore, pull requests merged in 2019-01, with the labels that each got.

#513 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  dev/src/v1beta1/doc/google/protobuf/doc_wrappers.js
  synth.metadata
Labels: cla: yes

#515 Overload getAll function to allow array destructuring
  dev/src/index.ts
  dev/src/transaction.ts
  dev/system-test/firestore.ts
  types/firestore.d.ts
Labels: cla: yes

#503 Cleanup: Remove `is`
  dev/conformance/runner.ts
  dev/src/document.ts
  dev/src/index.ts
  dev/src/path.ts
  dev/src/serializer.ts
  dev/test/timestamp.ts
  package.json
Labels: cla: yes

#495 Cleanup: Argument count validation
  dev/src/field-value.ts
  dev/src/index.ts
  dev/src/path.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/validate.ts
  dev/src/write-batch.ts
  dev/test/document.ts
  dev/test/query.ts
Labels: cla: yes

#496 Cleanup: Validate primitive types
  dev/src/convert.ts
  dev/src/geo-point.ts
  dev/src/index.ts
  dev/src/logger.ts
  dev/src/path.ts
  dev/src/reference.ts
  dev/src/timestamp.ts
  dev/src/util.ts
  dev/src/validate.ts
Labels: cla: yes

#506 Cleanup: Misc
  dev/src/document.ts
  dev/src/index.ts
  dev/src/order.ts
  dev/src/reference.ts
  dev/src/serializer.ts
  dev/src/transaction.ts
  dev/test/document.ts
  dev/test/order.ts
  dev/test/watch.ts
Labels: cla: yes

#511 build: check broken links in generated docs
  .jsdoc.js
  .kokoro/docs.sh
  dev/src/backoff.ts
  dev/src/document.ts
  dev/src/field-value.ts
  dev/src/pool.ts
  dev/src/reference.ts
  dev/src/v1beta1/doc/google/protobuf/doc_timestamp.js
  dev/src/validate.ts
  dev/src/watch.ts
  package.json
  synth.py
Labels: cla: yes

#521 feat: add additional field transform types
  dev/protos/google/firestore/v1beta1/common.proto
  dev/protos/google/firestore/v1beta1/document.proto
  dev/protos/google/firestore/v1beta1/firestore.proto
  dev/protos/google/firestore/v1beta1/query.proto
  dev/protos/google/firestore/v1beta1/write.proto
  dev/src/v1beta1/doc/google/firestore/v1beta1/doc_write.js
  synth.metadata
Labels: cla: yes

#507 Cleanup: Error messages for custom objects
  dev/src/validate.ts
Labels: cla: yes

#504 refactor: Add strict types for the transaction test
  dev/test/transaction.ts
Labels: cla: yes

#516 feat: update to v1 protos
  .gitignore
  README.md
  dev/conformance/runner.ts
  dev/conformance/test-definition.proto
  dev/protos/firestore_proto_api.d.ts
  dev/protos/firestore_proto_api.js
  dev/protos/google/firestore/v1/common.proto
  dev/protos/google/firestore/v1/document.proto
  dev/protos/google/firestore/v1/firestore.proto
  dev/protos/google/firestore/v1/query.proto
  dev/protos/google/firestore/v1/write.proto
  dev/protos/google/firestore/v1beta1/.DS_Store
  dev/protos/google/protobuf/timestamp.proto
  dev/protos/update.sh
  dev/src/convert.ts
  dev/src/document.ts
  dev/src/field-value.ts
  dev/src/geo-point.ts
  dev/src/index.ts
  dev/src/order.ts
  dev/src/path.ts
  dev/src/reference.ts
  dev/src/serializer.ts
  dev/src/transaction.ts
  dev/src/types.ts
  dev/src/v1/doc/google/firestore/v1/doc_common.js
  dev/src/v1/doc/google/firestore/v1/doc_document.js
  dev/src/v1/doc/google/firestore/v1/doc_firestore.js
  dev/src/v1/doc/google/firestore/v1/doc_query.js
  dev/src/v1/doc/google/firestore/v1/doc_write.js
  dev/src/v1/doc/google/protobuf/doc_any.js
  dev/src/v1/doc/google/protobuf/doc_empty.js
  dev/src/v1/doc/google/protobuf/doc_timestamp.js
  dev/src/v1/doc/google/protobuf/doc_wrappers.js
  dev/src/v1/doc/google/rpc/doc_status.js
  dev/src/v1/firestore_client.js
  dev/src/v1/firestore_client_config.json
  dev/src/v1/index.js
  dev/src/watch.ts
  dev/src/write-batch.ts
  dev/test/gapic-v1.js
  dev/test/index.ts
  dev/test/path.ts
  dev/test/query.ts
  dev/test/transaction.ts
  dev/test/util/helpers.ts
  dev/test/watch.ts
  package.json
  synth.metadata
  synth.py
Labels: cla: yes

#522 Release @google-cloud/firestore v0.20.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#523 chore: update year in the license headers
  dev/src/v1/doc/google/firestore/v1/doc_common.js
  dev/src/v1/doc/google/firestore/v1/doc_document.js
  dev/src/v1/doc/google/firestore/v1/doc_firestore.js
  dev/src/v1/doc/google/firestore/v1/doc_query.js
  dev/src/v1/doc/google/firestore/v1/doc_write.js
  dev/src/v1/doc/google/protobuf/doc_any.js
  dev/src/v1/doc/google/protobuf/doc_empty.js
  dev/src/v1/doc/google/protobuf/doc_timestamp.js
  dev/src/v1/doc/google/protobuf/doc_wrappers.js
  dev/src/v1/doc/google/rpc/doc_status.js
  dev/src/v1/firestore_client.js
  dev/src/v1/index.js
  dev/test/gapic-v1.js
  synth.metadata
Labels: cla: yes

#524 docs: fix import links in the jsdocs
  dev/src/v1/firestore_client.js
  synth.metadata
Labels: cla: yes

#527 build: ignore googleapis.com in doc link checker
  .kokoro/docs.sh
Labels: automerge, cla: yes

#530 Release @google-cloud/firestore v0.21.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#531 Release @google-cloud/firestore v1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#533 fix(samples): constructor doesn't need project or cred options
  samples/quickstart.js
Labels: cla: yes

#532 doc: update README.md to show this library as GA
  README.md
Labels: cla: yes

#534 Release @google-cloud/firestore v1.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#536 doc: show GA message in README.md
  .cloud-repo-tools.json
  README.md
Labels: cla: yes
