Repository googleapis/nodejs-firestore, pull requests merged in 2019-03, with the labels that each got.

#559 docs: update comments on protos
  dev/protos/google/firestore/v1/common.proto
  dev/protos/google/firestore/v1/document.proto
  dev/protos/google/firestore/v1/firestore.proto
  dev/protos/google/firestore/v1/query.proto
  dev/protos/google/firestore/v1/write.proto
  dev/src/v1/doc/google/firestore/v1/doc_common.js
  dev/src/v1/doc/google/firestore/v1/doc_firestore.js
  dev/src/v1/doc/google/firestore/v1/doc_write.js
  dev/src/v1/firestore_client.js
  synth.metadata
Labels: cla: yes

#563 Release @google-cloud/firestore v1.0.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#566 Introduce async/await to test/order.ts
  dev/test/order.ts
Labels: cla: yes

#565 Don't call stream.end() on Watch ended by server
  dev/src/reference.ts
  dev/src/watch.ts
  dev/test/watch.ts
Labels: cla: yes

#571 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#444 Adding Numeric Add
  dev/src/field-value.ts
  dev/src/index.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/validate.ts
  dev/system-test/firestore.ts
  dev/test/collection.ts
  dev/test/document.ts
  dev/test/field-value.ts
  dev/test/index.ts
  dev/test/path.ts
  dev/test/query.ts
  dev/test/timestamp.ts
  dev/test/transaction.ts
  dev/test/typescript.ts
  dev/test/util/helpers.ts
  dev/test/watch.ts
  dev/test/write-batch.ts
  types/firestore.d.ts
Labels: :rotating_light:, cla: yes

#570 build: update release config
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#572 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#576 [fix]: allow async functions in transactions
  dev/src/util.ts
Labels: cla: yes

#577 Release @google-cloud/firestore v1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#564 Removing @google-cloud/projectify
  dev/conformance/runner.ts
  dev/src/document.ts
  dev/src/index.ts
  dev/src/order.ts
  dev/src/path.ts
  dev/src/reference.ts
  dev/src/serializer.ts
  dev/src/timestamp.ts
  dev/src/validate.ts
  dev/src/watch.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/index.ts
  dev/test/order.ts
  dev/test/path.ts
  dev/test/query.ts
  dev/test/transaction.ts
  dev/test/util/helpers.ts
  dev/test/watch.ts
  package.json
Labels: :rotating_light:, cla: yes

#580 refactor: update json import paths
  dev/src/v1/firestore_client.js
  synth.metadata
Labels: cla: yes

#582 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#585 docs: fix typo in doc strings
  dev/protos/google/firestore/v1/write.proto
  dev/src/v1/doc/google/firestore/v1/doc_write.js
  synth.metadata
Labels: cla: yes

#586 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#591 fix(docs): add namespaces so docs are generated
  dev/src/index.ts
Labels: cla: yes

#590 feature: Release the V1 Admin API
  dev/protos/firestore_proto_api.d.ts
  dev/protos/firestore_proto_api.js
  dev/protos/google/api/http.proto
  dev/protos/google/firestore/admin/v1/field.proto
  dev/protos/google/firestore/admin/v1/firestore_admin.proto
  dev/protos/google/firestore/admin/v1/index.proto
  dev/protos/google/firestore/admin/v1/location.proto
  dev/protos/google/firestore/admin/v1/operation.proto
  dev/protos/google/firestore/v1/common.proto
  dev/protos/google/firestore/v1/document.proto
  dev/protos/google/firestore/v1/firestore.proto
  dev/protos/google/firestore/v1/query.proto
  dev/protos/google/firestore/v1/write.proto
  dev/protos/google/longrunning/operations.proto
  dev/protos/google/protobuf/field_mask.proto
  dev/protos/google/rpc/status.proto
  dev/protos/google/type/latlng.proto
  dev/protos/update.sh
  dev/src/v1/doc/google/firestore/admin/v1/doc_field.js
  dev/src/v1/doc/google/firestore/admin/v1/doc_firestore_admin.js
  dev/src/v1/doc/google/firestore/admin/v1/doc_index.js
  dev/src/v1/doc/google/firestore/v1/doc_common.js
  dev/src/v1/doc/google/firestore/v1/doc_firestore.js
  dev/src/v1/doc/google/firestore/v1/doc_query.js
  dev/src/v1/doc/google/firestore/v1/doc_write.js
  dev/src/v1/doc/google/longrunning/doc_operations.js
  dev/src/v1/doc/google/protobuf/doc_field_mask.js
  dev/src/v1/firestore_admin_client.js
  dev/src/v1/firestore_admin_client_config.json
  dev/src/v1/firestore_client.js
  dev/src/v1/index.js
  dev/test/gapic-v1.js
  package.json
  synth.metadata
  synth.py
  types/firestore.d.ts
Labels: cla: yes

#592 Release @google-cloud/firestore v1.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes
