Repository googleapis/nodejs-firestore, pull requests merged in 2019-05, with the labels that each got.

#607 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#608 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#609 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#610 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: cla: yes

#611 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: automerge, cla: yes

#612 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#614 fix: Fix client pooling for long-lived listens
  dev/src/index.ts
  dev/src/pool.ts
Labels: cla: yes

#616 fix: update request headers, formatting, and jsdoc
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  dev/src/v1/doc/google/firestore/admin/v1/doc_field.js
  dev/src/v1/doc/google/firestore/admin/v1/doc_firestore_admin.js
  dev/src/v1/doc/google/firestore/admin/v1/doc_index.js
  dev/src/v1/doc/google/firestore/v1/doc_common.js
  dev/src/v1/doc/google/firestore/v1/doc_document.js
  dev/src/v1/doc/google/firestore/v1/doc_firestore.js
  dev/src/v1/doc/google/firestore/v1/doc_query.js
  dev/src/v1/doc/google/firestore/v1/doc_write.js
  dev/src/v1/doc/google/longrunning/doc_operations.js
  dev/src/v1/doc/google/protobuf/doc_any.js
  dev/src/v1/doc/google/protobuf/doc_field_mask.js
  dev/src/v1/doc/google/protobuf/doc_timestamp.js
  dev/src/v1/doc/google/rpc/doc_status.js
  dev/src/v1/firestore_admin_client.js
  dev/src/v1/firestore_client.js
  samples/README.md
  synth.metadata
Labels: cla: yes

#617 docs: improve the quickstart
  README.md
  samples/quickstart.js
  synth.metadata
Labels: cla: yes

#620 [docs] Further improve quickstart.js
  samples/quickstart.js
  samples/system-test/quickstart.test.js
Labels: cla: yes

#622 docs: update the README to match the quickstart
  README.md
  synth.metadata
Labels: cla: yes

#627 fix(docs): revert jsdoc and pin to 3.5.5
  package.json
Labels: cla: yes

#624 refactor(deprecation)!: remove deprecated getCollections()
  dev/src/index.ts
  dev/src/reference.ts
  dev/test/document.ts
  dev/test/index.ts
  dev/test/typescript.ts
  types/firestore.d.ts
Labels: cla: yes

#623 fix: Support more than 100 long-lived streams
  dev/src/index.ts
  dev/src/pool.ts
  dev/src/util.ts
  dev/system-test/firestore.ts
  dev/test/collection.ts
  dev/test/document.ts
  dev/test/index.ts
  dev/test/order.ts
  dev/test/pool.ts
  dev/test/query.ts
  dev/test/util/helpers.ts
  dev/test/watch.ts
  dev/test/write-batch.ts
Labels: cla: yes

#625 refactor(deprecation)!: remove legacy support for array arguments
  dev/conformance/runner.ts
  dev/src/index.ts
  dev/src/path.ts
  dev/src/transaction.ts
  dev/test/index.ts
Labels: cla: yes

#630 build: Exclude Proto files from Coverage
  .nycrc
Labels: cla: yes

#636 build!: upgrade engines field to >=8.13.0
  package.json
Labels: cla: yes

#635 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#634 docs: Update sample to use non-default export
  dev/src/watch.ts
  dev/test/document.ts
  samples/quickstart.js
Labels: cla: yes

#644 docs: Update README.md
  README.md
  synth.metadata
Labels: cla: yes

#646 chore: release 2.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#642 refactor: modernize sample test
  samples/package.json
  samples/system-test/.eslintrc.yml
  samples/system-test/quickstart.test.js
  samples/test/.eslintrc.yml
  samples/test/quickstart.test.js
Labels: cla: yes

#628 docs: Remove @private from public classes
  dev/src/document-change.ts
  dev/src/document.ts
  dev/src/field-value.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/write-batch.ts
Labels: cla: yes

#647 Revert "fix(docs): revert jsdoc and pin to 3.5.5"
  dev/src/document.ts
  dev/src/write-batch.ts
  package.json
Labels: cla: yes

#648 chore: Update generated clients
  dev/src/v1/firestore_admin_client.js
  dev/src/v1/firestore_client.js
  synth.metadata
Labels: cla: yes

#650 chore: Include v1beta1 in synth.py
  dev/protos/google/firestore/v1beta1/common.proto
  dev/protos/google/firestore/v1beta1/document.proto
  dev/protos/google/firestore/v1beta1/firestore.proto
  dev/protos/google/firestore/v1beta1/query.proto
  dev/protos/google/firestore/v1beta1/write.proto
  dev/src/v1beta1/doc/google/firestore/v1beta1/doc_common.js
  dev/src/v1beta1/doc/google/firestore/v1beta1/doc_document.js
  dev/src/v1beta1/doc/google/firestore/v1beta1/doc_firestore.js
  dev/src/v1beta1/doc/google/firestore/v1beta1/doc_query.js
  dev/src/v1beta1/doc/google/firestore/v1beta1/doc_write.js
  dev/src/v1beta1/doc/google/protobuf/doc_any.js
  dev/src/v1beta1/doc/google/protobuf/doc_empty.js
  dev/src/v1beta1/doc/google/protobuf/doc_timestamp.js
  dev/src/v1beta1/doc/google/protobuf/doc_wrappers.js
  dev/src/v1beta1/doc/google/rpc/doc_status.js
  dev/src/v1beta1/firestore_client.js
  dev/src/v1beta1/index.js
  dev/test/gapic-v1beta1.js
  synth.metadata
  synth.py
Labels: cla: yes

#652 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#649 deps: Remove dependency on lodash.merge
  package.json
Labels: cla: yes, kokoro: force-run

#653 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#654 feat: Support listDocuments()/listCollections() via the Firestore Emulator
  dev/src/index.ts
Labels: cla: yes

#655 fix: retry on abort and limit retry count to 10
  dev/src/backoff.ts
  dev/src/watch.ts
  dev/test/backoff.ts
  dev/test/watch.ts
Labels: cla: yes

#663 Add IntelliJ test runners
  .idea/runConfigurations/Conformance_Tests.xml
  .idea/runConfigurations/System_Test.xml
  .idea/runConfigurations/Unit_Tests.xml
Labels: cla: yes

#662 fix: Add overloads for doc() and doc(id:string)
  dev/src/reference.ts
  dev/test/collection.ts
  types/firestore.d.ts
Labels: cla: yes

#657 chore: release 2.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#664 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#665 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#668 deps: Pin @gprc/grpc-js to 0.4.0
  package.json
Labels: cla: yes

#670 Release @google-cloud/firestore v2.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes
