Repository googleapis/nodejs-firestore, pull requests merged in 2020-04, with the labels that each got.

#996 build: set AUTOSYNTH_MULTIPLE_COMMITS=true for context aware commits
  synth.py
Labels: automerge, cla: yes

#995 docs: change batch() code sample
  dev/src/index.ts
Labels: api: firestore, cla: yes

#1001 chore: remove duplicate mocha config
  .mocharc.json
Labels: automerge, cla: yes

#1003 fix: validate nested arrays in FieldValue
  dev/src/field-value.ts
  dev/test/field-value.ts
Labels: cla: yes

#937 fix!: mark v1beta1 client as deprecated
  dev/src/v1beta1/firestore_client.ts
  dev/src/v1beta1/index.ts
  dev/synth.metadata
  synth.py
  types/firestore.d.ts
Labels: cla: yes, do not merge

#965 feat!: use QueryDocumentSnapshot in FirestoreDataConverter
  dev/src/document.ts
  dev/src/reference.ts
  dev/src/types.ts
  dev/test/typescript.ts
  dev/test/util/helpers.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes, do not merge

#1011 build: remove unused codecov config
  codecov.yaml
Labels: automerge, cla: yes

#1015 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#1019 chore!: update settings for Node 10
  .eslintignore
  .github/workflows/ci.yaml
  .gitignore
  .jsdoc.js
  .mocharc.js
  .prettierignore
  .prettierrc.js
  README.md
  dev/.gitignore
  dev/.mocharc.json
  dev/protos/firestore_admin_v1_proto_api.d.ts
  dev/protos/firestore_admin_v1_proto_api.js
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/firestore_v1beta1_proto_api.d.ts
  dev/protos/firestore_v1beta1_proto_api.js
  dev/protos/google/api/resource.proto
  dev/protos/google/rpc/status.proto
  dev/protos/google/type/latlng.proto
  dev/protos/protos.json
  dev/protos/update.sh
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  dev/test/gapic_firestore_admin_v1.ts
  dev/test/gapic_firestore_v1.ts
  dev/test/gapic_firestore_v1beta1.ts
  package.json
  synth.metadata
  synth.py
  tslint.json
Labels: cla: yes

#1021 feat: add rate limiter class
  dev/src/rate-limiter.ts
  dev/test/rate-limiter.ts
Labels: cla: yes

#1014 deps: drop through2
  dev/src/index.ts
  dev/src/reference.ts
  package.json
Labels: cla: yes

#1018 feat: Add BulkWriter base
  dev/src/bulk-writer.ts
  dev/src/index.ts
  dev/test/bulk-writer.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1016 feat: support BigInt
  dev/protos/firestore_admin_v1_proto_api.d.ts
  dev/protos/firestore_admin_v1_proto_api.js
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/firestore_v1beta1_proto_api.d.ts
  dev/protos/firestore_v1beta1_proto_api.js
  dev/protos/update.sh
  dev/src/convert.ts
  dev/src/index.ts
  dev/src/serializer.ts
  dev/src/timestamp.ts
  dev/src/types.ts
  dev/system-test/firestore.ts
  dev/test/document.ts
  dev/test/util/helpers.ts
  synth.metadata
  types/firestore.d.ts
Labels: cla: yes

#1033 feat: add 555 rule support
  dev/src/backoff.ts
  dev/src/bulk-writer.ts
  dev/src/index.ts
  dev/src/rate-limiter.ts
  dev/src/types.ts
  dev/test/bulk-writer.ts
  types/firestore.d.ts
Labels: cla: yes

#1032 feat: add bundle.proto and generated js code
  dev/protos/firestore/bundle.proto
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/google/api/resource.proto
  dev/protos/google/rpc/status.proto
  dev/protos/google/type/latlng.proto
  dev/protos/update.sh
Labels: api: firestore, cla: yes

#1034 feat: Add support to convert a Query to a BundledQuery.
  dev/src/reference.ts
  dev/test/query.ts
Labels: cla: yes

#1036 Make BulkWriter private until protos are released
  dev/src/bulk-writer.ts
  dev/src/index.ts
  dev/test/bulk-writer.ts
  types/firestore.d.ts
Labels: cla: yes

#1037 Add converter support
  dev/src/bulk-writer.ts
  dev/test/bulk-writer.ts
Labels: cla: yes

#1042 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes

#1043 fix: make update.sh work on Linux
  dev/protos/update.sh
Labels: cla: yes

#1045 chore: run synthtool
  .github/workflows/ci.yaml
  dev/protos/firestore_admin_v1_proto_api.js
  dev/protos/firestore_v1_proto_api.js
  dev/protos/firestore_v1beta1_proto_api.js
  dev/protos/update.sh
  synth.metadata
Labels: api: firestore, cla: yes

#1046 fix: return errors from Query.stream()
  dev/src/reference.ts
  dev/test/query.ts
Labels: cla: yes

#1053 fix: Fix BulkWriter comments
  dev/src/index.ts
Labels: cla: yes

#1056 chore: add vscode files
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
Labels: cla: yes

#1059 docs: Add documentation for FirestoreDataConverter
  dev/src/index.ts
  dev/src/reference.ts
Labels: cla: yes
