Repository googleapis/nodejs-firestore, pull requests merged in 2020-10, with the labels that each got.

#1321 fix: simplify BulkWriter logic
  dev/src/write-batch.ts
Labels: cla: yes

#1320 feat: add support for Partition API
  dev/src/bulk-writer.ts
  dev/src/collection-group.ts
  dev/src/document-change.ts
  dev/src/document.ts
  dev/src/field-value.ts
  dev/src/index.ts
  dev/src/query-partition.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/types.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/partition-query.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1329 chore: stop Synthtool from deleting reference.ts
  synth.metadata
Labels: automerge, cla: yes

#1333 chore: update generated Proto code
  .trampolinerc
  dev/protos/firestore_admin_v1_proto_api.d.ts
  dev/protos/firestore_admin_v1_proto_api.js
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/firestore_v1beta1_proto_api.d.ts
  dev/protos/firestore_v1beta1_proto_api.js
  dev/protos/google/api/resource.proto
  synth.metadata
Labels: cla: yes, context: partial

#1335 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1334 fix(firestore/v1): give PartitionQuery retry/timeout config
  dev/src/v1/firestore_client_config.json
  synth.metadata
Labels: cla: yes, context: full

#1336 fix: retry PartitionQuery for INTERNAL and DEADLINE_EXCEEDED
  dev/src/v1/firestore_client_config.json
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#1328 feat: add implicit ordering for startAt(DocumentReference) calls
  dev/src/reference.ts
  dev/system-test/firestore.ts
  dev/test/query.ts
Labels: api: firestore, cla: yes

#1326 docs: update getAll example in documentation
  dev/src/reference.ts
Labels: api: firestore, cla: yes

#1338 fix: update required field to implement NodeJS.Timeout
  dev/src/backoff.ts
Labels: cla: yes

#1340 docs: update to comments in protos
  dev/protos/google/type/latlng.proto
  synth.metadata
Labels: cla: yes, context: partial

#1344 fix: speed up listDocuments pagination
  dev/src/reference.ts
  dev/test/collection.ts
Labels: api: firestore, cla: yes

#1346 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: automerge, cla: yes, context: full
