Repository googleapis/nodejs-firestore, pull requests merged in 2020-07, with the labels that each got.

#1254 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#1252 feat: make BulkWriter public
  dev/src/bulk-writer.ts
  dev/src/index.ts
  dev/src/types.ts
  dev/system-test/firestore.ts
  dev/test/bulk-writer.ts
  types/firestore.d.ts
Labels: cla: yes

#1255 chore: revert "feat: add deprecation message to WriteBatch (#1251)"
  dev/src/index.ts
  dev/src/write-batch.ts
  types/firestore.d.ts
Labels: cla: yes

#1256 chore: update CHANGELOG
  CHANGELOG.md
Labels: cla: yes

#1257 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#1260 build: use bazel build in synthtool
  dev/protos/firestore_admin_v1_proto_api.js
  dev/protos/firestore_v1_proto_api.js
  dev/protos/firestore_v1beta1_proto_api.js
  synth.metadata
  synth.py
Labels: cla: yes

#1263 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#1261 build: typo from .gittatributes fix
  dev/protos/firestore_admin_v1_proto_api.js
  dev/protos/firestore_v1_proto_api.js
  dev/protos/firestore_v1beta1_proto_api.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#1266 chore: add config files for cloud-rad for node.js
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#1268 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#1272 fix: add Firestore.bulkWriter to firestore.d.ts
  types/firestore.d.ts
Labels: cla: yes

#1273 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:run

#1275 feat: allow `Settings.host` to be used when `Settings.servicePath` is set
  dev/src/index.ts
  dev/test/index.ts
Labels: cla: yes

#1278 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#1277 chore: add firestore to CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes
