Repository googleapis/nodejs-firestore, pull requests merged in 2020-02, with the labels that each got.

#906 chore: skip img.shields.io in docs test
  linkinator.config.json
Labels: cla: yes

#905 test: modernize mocha config
  .mocharc.json
  dev/test/mocha.opts
  package.json
Labels: cla: yes

#917 fix: add missing generics on query
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#912 feat: add google-gax status to exports
  dev/src/index.ts
  dev/test/typescript.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#920 fix: pass x-goog-request-params header for streaming calls
  dev/.gitignore
  dev/.mocharc.json
  dev/protos/protos.json
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_admin_proto_list.json
  dev/src/v1/firestore_client.ts
  dev/src/v1/firestore_proto_list.json
  dev/src/v1beta1/firestore_client.ts
  dev/src/v1beta1/firestore_proto_list.json
  dev/synth.metadata
  dev/test/gapic-firestore-v1.ts
  dev/test/gapic-firestore-v1beta1.ts
  dev/test/gapic-firestore_admin-v1.ts
Labels: cla: yes

#926 build: add GitHub actions config for unit tests
  .github/workflows/ci.yaml
  package.json
Labels: cla: yes

#925 fix: collectionReference.add() validation
  dev/src/reference.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/collection.ts
Labels: api: firestore, cla: yes

#931 fix: propagate converter in QueryOptions.with()
  dev/src/reference.ts
  dev/test/query.ts
Labels: api: firestore, cla: yes

#915 fix: wait for operations to complete before deleting clients
  dev/src/index.ts
  dev/src/pool.ts
  dev/src/watch.ts
  dev/system-test/firestore.ts
  dev/test/pool.ts
Labels: api: firestore, cla: yes

#935 chore: update protos
  dev/protos/google/longrunning/operations.proto
  dev/protos/google/rpc/status.proto
Labels: api: firestore, cla: yes

#940 chore: add update_transform
  dev/protos/google/firestore/v1/common.proto
  dev/protos/google/firestore/v1/document.proto
  dev/protos/google/firestore/v1/firestore.proto
  dev/protos/google/firestore/v1/query.proto
  dev/protos/google/firestore/v1/write.proto
  dev/protos/protos.json
  dev/src/v1/firestore_client.ts
  dev/src/v1/firestore_client_config.json
  dev/synth.metadata
  dev/test/gapic-firestore-v1.ts
Labels: cla: yes

#941 build: add publish.yml enabling GitHub app for publishes
  .github/publish.yml
Labels: automerge, cla: yes

#942 chore: update jsdoc.js
  .jsdoc.js
Labels: automerge, cla: yes

#946 chore: update jsdoc with macro license
  .jsdoc.js
Labels: automerge, cla: yes
