Repository googleapis/nodejs-firestore, pull requests merged in 2020-11, with the labels that each got.

#1347 fix: retry transactions that fail with expired transaction IDs
  dev/src/transaction.ts
  dev/test/transaction.ts
Labels: api: firestore, cla: yes

#1315 feat: add onWriteError() and onWriteResult() handlers to BulkWriter
  dev/src/bulk-writer.ts
  dev/src/util.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/bulk-writer.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1352 fix: create new batch for writes to the same doc
  dev/src/bulk-writer.ts
  dev/system-test/firestore.ts
  dev/test/bulk-writer.ts
Labels: api: firestore, cla: yes

#1355 feat: add ability to specify custom headers for individual RPC types
  dev/src/index.ts
Labels: api: firestore, cla: yes

#1354 chore: refactor BulkCommitBatch
  dev/src/bulk-writer.ts
  dev/src/write-batch.ts
  dev/test/write-batch.ts
Labels: api: firestore, cla: yes

#1361 fix: remove unneeded async signature from BulkWriter.sendBatch()
  dev/src/bulk-writer.ts
Labels: api: firestore, cla: yes

#1360 fix: do not modify options object, use defaultScopes
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  package.json
  synth.metadata
Labels: api: firestore, automerge, cla: yes

#1363 fix: ignore 'undefined' in update() with UpdateMap
  dev/src/serializer.ts
  dev/src/write-batch.ts
  dev/test/ignore-undefined.ts
Labels: api: firestore, cla: yes

#1364 docs: add GrpcStatus to JSDoc, hide other private APIs
  dev/src/bulk-writer.ts
  dev/src/index.ts
  dev/src/util.ts
  dev/src/watch.ts
Labels: api: firestore, cla: yes

#1368 fix(browser): check for fetch on window
  dev/protos/protos.json
  dev/src/reference.ts
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  dev/system-test/firestore.ts
  dev/test/watch.ts
  synth.metadata
  types/firestore.d.ts
Labels: api: firestore, cla: yes, context: none

#1371 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full
