Repository googleapis/nodejs-firestore, pull requests merged in 2020-06, with the labels that each got.

#1105 fix: send Authentication header with every emulator request
  dev/src/index.ts
Labels: cla: yes

#1100 chore: use public API types internally
  dev/conformance/runner.ts
  dev/src/bulk-writer.ts
  dev/src/document-change.ts
  dev/src/document.ts
  dev/src/field-value.ts
  dev/src/geo-point.ts
  dev/src/index.ts
  dev/src/path.ts
  dev/src/reference.ts
  dev/src/serializer.ts
  dev/src/timestamp.ts
  dev/src/transaction.ts
  dev/src/types.ts
  dev/src/util.ts
  dev/src/watch.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/bulk-writer.ts
  dev/test/query.ts
  dev/test/util/helpers.ts
  dev/test/watch.ts
  dev/test/write-batch.ts
Labels: cla: yes

#1110 feat: add Partition and BatchWrite protos
  .eslintignore
  .github/workflows/ci.yaml
  .mocharc.js
  .prettierrc.js
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/google/firestore/v1/firestore.proto
  dev/protos/google/firestore/v1/query.proto
  dev/protos/protos.json
  dev/src/v1/firestore_client.ts
  dev/src/v1/firestore_client_config.json
  dev/test/bulk-writer.ts
  dev/test/gapic_firestore_v1.ts
  synth.metadata
  synth.py
Labels: cla: yes

#1112 fix: remove GCF transaction fallback
  dev/src/index.ts
  dev/src/transaction.ts
  dev/src/write-batch.ts
  dev/test/write-batch.ts
Labels: cla: yes

#1118 build: update system-test and sample-test config
  .kokoro/populate-secrets.sh
  .kokoro/pre-samples-test.sh
  .kokoro/pre-system-test.sh
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/setup-vars.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#1114 deps: update google-gax
  package.json
Labels: cla: yes

#1115 fix: fix flaky BulkWriter test
  dev/test/bulk-writer.ts
Labels: cla: yes

#1111 fix: retry ABORTED for non-transactional commits
  dev/src/index.ts
  dev/src/util.ts
  dev/src/write-batch.ts
  dev/test/bulk-writer.ts
  dev/test/transaction.ts
  dev/test/write-batch.ts
Labels: cla: yes

#1116 fix: retry Query streams
  dev/src/document.ts
  dev/src/reference.ts
  dev/test/query.ts
Labels: cla: yes

#1216 chore: update credentials for continuous build
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
Labels: cla: yes

#1113 docs: sample for limitToLast() query
  samples/limit-to-last-query.js
  samples/test/limit-to-last-query.test.js
Labels: cla: yes

#1218 chore: merge master
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/pre-samples-test.sh
  .kokoro/pre-system-test.sh
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test.cfg
  .kokoro/setup-vars.sh
  .kokoro/trampoline.sh
  CHANGELOG.md
  dev/src/bulk-writer.ts
  dev/src/document.ts
  dev/src/index.ts
  dev/src/path.ts
  dev/src/reference.ts
  dev/src/util.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/bulk-writer.ts
  dev/test/collection.ts
  dev/test/query.ts
  dev/test/transaction.ts
  dev/test/write-batch.ts
  package.json
  samples/limit-to-last-query.js
  samples/package.json
  samples/test/limit-to-last-query.test.js
Labels: cla: no

#1224 fix: reject all promises with errors
  dev/src/pool.ts
  dev/src/util.ts
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  dev/system-test/firestore.ts
  dev/test/pool.ts
Labels: cla: yes

#1227 tests: fix LimitToLast quickstart
  samples/test/limit-to-last-query.test.js
Labels: cla: yes

#1229 chore: add eslint check for console.log statements
  .eslintrc.json
  dev/src/bulk-writer.ts
Labels: cla: yes

#1230 build: do not overwrite custom env vars
  synth.py
Labels: cla: yes

#1220 fix: restart onSnapshot() listeners that stop receiving updates
  dev/src/backoff.ts
  dev/src/watch.ts
  dev/test/backoff.ts
  dev/test/bulk-writer.ts
  dev/test/index.ts
  dev/test/query.ts
  dev/test/transaction.ts
  dev/test/watch.ts
Labels: cla: yes

#1228 fix: another attempt at fixing the flaky BulkWriter test
  dev/test/bulk-writer.ts
Labels: cla: yes

#1235 chore: run synthtool after node10 merge
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/google/api/client.proto
  dev/protos/google/api/field_behavior.proto
  dev/protos/google/api/http.proto
  dev/protos/google/api/resource.proto
  dev/protos/google/firestore/admin/v1/field.proto
  dev/protos/google/firestore/admin/v1/firestore_admin.proto
  dev/protos/google/firestore/admin/v1/index.proto
  dev/protos/google/firestore/admin/v1/location.proto
  dev/protos/google/firestore/admin/v1/operation.proto
  dev/protos/google/firestore/v1/common.proto
  dev/protos/google/firestore/v1/document.proto
  dev/protos/google/firestore/v1/firestore.proto
  dev/protos/google/firestore/v1/query.proto
  dev/protos/google/firestore/v1/write.proto
  dev/protos/google/firestore/v1beta1/common.proto
  dev/protos/google/firestore/v1beta1/document.proto
  dev/protos/google/firestore/v1beta1/firestore.proto
  dev/protos/google/firestore/v1beta1/query.proto
  dev/protos/google/firestore/v1beta1/write.proto
  dev/protos/protos.json
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1/firestore_client_config.json
  dev/src/v1beta1/firestore_client.ts
  samples/README.md
  synth.metadata
  synth.py
Labels: cla: yes

#1242 feat: Retry BatchWrite RPC that fail with UNAVAILABLE and ABORTED
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/google/firestore/v1/query.proto
  dev/protos/protos.json
  dev/src/v1/firestore_client_config.json
  synth.metadata
Labels: cla: yes

#1247 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#1243 fix: retry ABORTED writes in bulkCommit
  dev/src/bulk-writer.ts
  dev/src/write-batch.ts
  dev/test/bulk-writer.ts
  dev/test/write-batch.ts
Labels: cla: yes

#1250 fix: update maximum batch size in BulkWriter
  dev/src/bulk-writer.ts
Labels: cla: yes

#1251 feat: add deprecation message to WriteBatch
  dev/src/index.ts
  dev/src/write-batch.ts
  types/firestore.d.ts
Labels: cla: yes
