Repository googleapis/nodejs-firestore, pull requests merged in 2020-09, with the labels that each got.

#1294 build: update kokoro config
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  dev/src/reference.ts
Labels: api: firestore, cla: yes

#1292 feat: add support for != and not-in queries
  dev/src/reference.ts
  dev/system-test/firestore.ts
  dev/test/query.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1301 test(conformance): fix invalid operator in where clause test
  dev/conformance/conformance-tests/query-invalid-operator.json
Labels: cla: yes

#1304 fix: allow `setLogFunction(null)`
  dev/src/logger.ts
  dev/test/bulk-writer.ts
  dev/test/collection.ts
  dev/test/document.ts
  dev/test/index.ts
  dev/test/order.ts
  dev/test/query.ts
  dev/test/transaction.ts
  dev/test/watch.ts
  dev/test/write-batch.ts
Labels: cla: yes

#1303 fix: change typings for select() to return Query<DocumentData>
  dev/src/reference.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1298 fix: bulkWriter: writing to the same document does not create a new batch
  dev/src/bulk-writer.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/bulk-writer.ts
Labels: api: firestore, cla: yes

#1308 docs: expand on FieldPath docstr
  dev/src/path.ts
Labels: cla: yes

#1305 feat: add starting/max rates to BulkWriterOptions
  dev/src/bulk-writer.ts
  dev/src/index.ts
  dev/src/rate-limiter.ts
  dev/test/bulk-writer.ts
  dev/test/rate-limiter.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1307 fix: fix flaky BulkWriter rate limiter test
  dev/src/bulk-writer.ts
  dev/test/bulk-writer.ts
Labels: api: firestore, cla: yes

#1311 build: generate config
  .github/publish.yml
  .github/workflows/ci.yaml
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .mocharc.js
Labels: cla: yes

#1291 chore: formatting
  synth.metadata
Labels: api: firestore, cla: yes, context: partial
