Repository googleapis/nodejs-firestore, pull requests merged in 2020-03, with the labels that each got.

#948 chore: run update.sh on update_transfrom protos
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
Labels: api: firestore, cla: yes

#947 feat: implement Timestamp.valueOf() (#944)
  dev/src/timestamp.ts
  dev/test/timestamp.ts
  types/firestore.d.ts
Labels: cla: yes

#952 refactor: use constants for MIN_SECONDS and MAX_SECONDS in Timestamp
  dev/src/timestamp.ts
Labels: cla: yes

#950 tests: set database in generated tests
  dev/synth.metadata
  dev/test/gapic-firestore-v1.ts
  dev/test/gapic-firestore-v1beta1.ts
Labels: cla: yes

#956 feat: deferred client initialization
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  dev/synth.metadata
  dev/test/gapic-firestore-v1.ts
  dev/test/gapic-firestore-v1beta1.ts
  dev/test/gapic-firestore_admin-v1.ts
Labels: automerge, cla: yes

#957 build: update linkinator config
  linkinator.config.json
Labels: automerge, cla: yes

#958 build(tests): fix coveralls and enable build cop
  .github/workflows/ci.yaml
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .mocharc.js
Labels: automerge, cla: yes

#953 feat: base transaction retries on error codes
  dev/src/transaction.ts
  dev/system-test/firestore.ts
  dev/test/transaction.ts
Labels: cla: yes

#949 feat: use update_transform when possible
  dev/src/document.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/document.ts
  dev/test/field-value.ts
  dev/test/util/helpers.ts
  dev/test/write-batch.ts
Labels: cla: yes

#962 deps: update TypeScript
  package.json
Labels: cla: yes

#954 feat: add support for Query.limitToLast()
  dev/src/reference.ts
  dev/system-test/firestore.ts
  dev/test/query.ts
  dev/test/typescript.ts
  types/firestore.d.ts
Labels: cla: yes

#961 feat: add BatchWriteRequests to WriteBatch.commit()
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/google/firestore/v1/firestore.proto
  dev/src/types.ts
  dev/src/write-batch.ts
  dev/test/write-batch.ts
Labels: cla: yes

#971 fix: support Query.stream() as first client operation
  dev/src/reference.ts
  dev/system-test/firestore.ts
  dev/test/query.ts
Labels: cla: yes

#974 docs: mention templates in contributing section of README
  README.md
Labels: automerge, cla: yes

#979 fix: fix flaky contention test
  dev/system-test/firestore.ts
Labels: cla: yes

#983 docs: document version support goals
  README.md
Labels: automerge, cla: yes

#966 refactor: drop duplicate constructor
  dev/src/document.ts
Labels: cla: yes

#984 Use Random Number from `crypto` to generate AutoId.
  dev/src/util.ts
Labels: api: firestore, cla: yes

#982 chore: regenerate the code
  .github/workflows/ci.yaml
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  dev/synth.metadata
  dev/test/gapic-firestore-v1.ts
  dev/test/gapic-firestore-v1beta1.ts
  dev/test/gapic-firestore_admin-v1.ts
Labels: automerge, cla: yes

#985 Revert "Use Random Number from `crypto` to generate AutoId."
  dev/src/util.ts
Labels: cla: yes

#986 fix: use Random Number from `crypto` to generate AutoId
  dev/src/util.ts
Labels: cla: yes

#993 fix: support array of references for IN queries
  dev/src/reference.ts
  dev/system-test/firestore.ts
  dev/test/query.ts
Labels: cla: yes
