Repository googleapis/nodejs-firestore, pull requests merged in 2021-09, with the labels that each got.

#1601 fix(build): migrate to main branch
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  README.md
  samples/README.md
Labels: cla: yes, automerge, api: firestore

#1604 chore: upgrade typescript to v4.4.2
  package.json
  tsconfig.json
Labels: cla: yes, api: firestore

#1608 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, automerge, api: firestore

#1607 chore: typo in bundle code sample
  dev/src/bundle.ts
Labels: cla: yes, api: firestore, samples

#1612 docs: fix typo in variable name
  dev/src/index.ts
Labels: cla: yes, api: firestore
