Repository googleapis/nodejs-firestore, pull requests merged in 2021-08, with the labels that each got.

#1575 fix: avoid destructuring undefined timestamps
  dev/src/convert.ts
Labels: api: firestore, cla: yes

#1578 chore(nodejs): update client ref docs link in metadata
  .repo-metadata.json
Labels: api: firestore, automerge, cla: yes

#1573 build: update auto-approve config for new validation
  .github/auto-approve.yml
  synth.metadata
Labels: cla: yes, automerge, api: firestore, context: full

#1585 docs: update link to reference documentation
  README.md
  synth.metadata
Labels: cla: yes, api: firestore, context: none

#1586 docs(nodejs): move branch references to main
  README.md
  synth.metadata
Labels: cla: yes, api: firestore, context: full

#1587 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  .vscode/launch.json
  .vscode/settings.json
  owlbot.py
  synth.metadata
  synth.py
Labels: cla: yes, api: firestore

#1588 fix(deps): google-gax v2.24.1
  package.json
Labels: cla: yes, automerge, api: firestore

#1592 chore!: upgrade typescript to v4.1.5
  dev/conformance/runner.ts
  dev/src/util.ts
  dev/system-test/firestore.ts
  dev/test/index.ts
  dev/test/pool.ts
  package.json
Labels: cla: yes, api: firestore

#1595 feat!: add QoL improvements for converters
  dev/src/bulk-writer.ts
  dev/src/document-change.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/types.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/util/helpers.ts
  types/firestore.d.ts
Labels: cla: yes, api: firestore
