Repository googleapis/nodejs-firestore, pull requests merged in 2021-05, with the labels that each got.

#1494 feat: add recursive delete to Firestore class
  dev/src/bulk-writer.ts
  dev/src/index.ts
  dev/src/recursive-delete.ts
  dev/src/reference.ts
  dev/system-test/firestore.ts
  dev/test/bulk-writer.ts
  dev/test/query.ts
  dev/test/recursive-delete.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1497 fix(deps): require google-gax v2.12.0
  package.json
Labels: api: firestore, automerge, cla: yes

#1500 chore: use require() to load JSON protos
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  synth.metadata
  types/protos/firestore_admin_v1_proto_api.d.ts
  types/protos/firestore_v1_proto_api.d.ts
  types/protos/firestore_v1beta1_proto_api.d.ts
Labels: api: firestore, cla: yes, context: partial

#1502 chore: code format
  .github/workflows/ci.yaml
  dev/src/backoff.ts
  dev/src/bulk-writer.ts
  dev/src/collection-group.ts
  dev/src/document-change.ts
  dev/src/document.ts
  dev/src/index.ts
  dev/src/query-partition.ts
  dev/src/recursive-delete.ts
  dev/src/reference.ts
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  dev/src/watch.ts
  dev/system-test/firestore.ts
  dev/test/bundle.ts
  dev/test/collection.ts
  dev/test/gapic_firestore_admin_v1.ts
  dev/test/gapic_firestore_v1.ts
  dev/test/gapic_firestore_v1beta1.ts
  dev/test/pool.ts
  dev/test/recursive-delete.ts
  dev/test/watch.ts
  synth.metadata
Labels: api: firestore, cla: yes, context: partial

#1504 docs: update and fix BulkWriter docs
  dev/src/bulk-writer.ts
Labels: api: firestore, cla: yes

#1505 docs: add Precondition.exists to delete()
  dev/src/index.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1506 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#1514 fix: recursive delete: backporting changes from Java
  dev/src/index.ts
  dev/src/recursive-delete.ts
  dev/test/recursive-delete.ts
Labels: api: firestore, cla: yes

#1518 docs: update BulkWriterError documentation
  dev/src/index.ts
Labels: api: firestore, cla: yes

#1517 fix: do not load google-gax at client startup
  dev/src/bulk-writer.ts
  dev/src/bundle.ts
  dev/src/index.ts
  dev/src/recursive-delete.ts
  dev/src/reference.ts
  dev/src/status-code.ts
  dev/src/transaction.ts
  dev/src/util.ts
  dev/src/write-batch.ts
  dev/test/lazy-load.ts
Labels: api: firestore, cla: yes

#1511 chore: update gapic-generator-typescript to v1.3.2
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#1521 fix: return results from getPartitions() in order
  dev/src/collection-group.ts
  dev/src/order.ts
  dev/test/partition-query.ts
Labels: api: firestore, cla: yes

#1522 fix: do not leak credentials in Firestore.toJSON()
  dev/src/index.ts
Labels: api: firestore, cla: yes

#1526 fix: GoogleAdsError missing using generator version after 1.3.0
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  synth.metadata
Labels: api: firestore, cla: yes, context: full
