Repository googleapis/nodejs-firestore, pull requests merged in 2021-02, with the labels that each got.

#1403 [chore] update copyright in Proto
  dev/protos/google/longrunning/operations.proto
  synth.metadata
Labels: api: firestore, cla: yes, context: none

#1404 docs: Add callback details for updateFunction in runTransaction()
  dev/src/index.ts
Labels: api: firestore, cla: yes

#1405 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: api: firestore, automerge, cla: yes

#1407 build: adds UNORDERED_LIST enum to proto
  dev/protos/google/api/field_behavior.proto
  dev/protos/protos.json
  synth.metadata
Labels: api: firestore, cla: yes, context: none

#1400 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
Labels: api: firestore, automerge, cla: yes

#1411 chore: use repo metadata to populate nodejs CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#1395 fix: support byte values in Bundles
  dev/src/bundle.ts
  dev/src/document.ts
  dev/src/timestamp.ts
  dev/system-test/firestore.ts
  dev/test/bundle.ts
  dev/test/document.ts
  dev/test/index.ts
  dev/test/util/helpers.ts
Labels: api: firestore, cla: yes

#1414 chore: update custom CODEOWNERS
  .github/CODEOWNERS
  synth.py
Labels: api: firestore, cla: yes

#1410 chore: small BulkWriter cleanup
  dev/src/bulk-writer.ts
Labels: api: firestore, automerge, cla: yes

#1417 fix: Use `Array.isArray` instead of an `instanceof` check
  dev/src/serializer.ts
Labels: api: firestore, cla: yes

#1416 chore: clean up before running Sample test
  samples/solution-counters.js
Labels: api: firestore, cla: yes

#1412 chore: add option to fetch all descendants
  dev/src/index.ts
  dev/src/path.ts
  dev/src/reference.ts
  dev/system-test/firestore.ts
Labels: api: firestore, cla: yes

#1423 docs: tweak wording of jsdoc
  dev/protos/google/longrunning/operations.proto
  synth.metadata
Labels: api: firestore, cla: yes, context: none

#1425 fix: promote "protobufjs" to a dependency from a devDependency
  package.json
Labels: api: firestore, cla: yes

#1427 feat: add recursiveDelete()
  dev/src/bulk-writer.ts
  dev/src/index.ts
  dev/system-test/firestore.ts
  dev/test/bulk-writer.ts
  dev/test/query.ts
  dev/test/recursive-delete.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes
