Repository googleapis/nodejs-firestore, pull requests merged in 2021-07, with the labels that each got.

#1553 build: automatically merge renovate PRs
  .github/auto-approve.yml
  dev/protos/firestore_admin_v1_proto_api.d.ts
  dev/protos/firestore_admin_v1_proto_api.js
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/firestore_v1beta1_proto_api.d.ts
  dev/protos/firestore_v1beta1_proto_api.js
  dev/protos/google/api/field_behavior.proto
  synth.metadata
Labels: api: firestore, cla: yes, context: partial

#1557 fix(deps): google-gax v2.17.1
  package.json
Labels: api: firestore, automerge, cla: yes

#1556 fix: lower batch size on BulkWriter retry to stay under throughput limits
  dev/src/bulk-writer.ts
  dev/test/bulk-writer.ts
Labels: api: firestore, cla: yes

#1554 feat: add "NON_EMPTY_DEFAULT" FieldBehavior
  dev/protos/protos.json
  synth.metadata
  types/protos/firestore_admin_v1_proto_api.d.ts
  types/protos/firestore_v1_proto_api.d.ts
  types/protos/firestore_v1beta1_proto_api.d.ts
Labels: api: firestore, cla: yes, context: none

#1567 chore: use cloud-rad publication process
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
Labels: api: firestore, cla: yes

#1568 docs: unhide withConverter docs
  dev/src/reference.ts
Labels: api: firestore, cla: yes

#1569 build: switch to release-please release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#1570 chore: annotate private APIs with @internal
  dev/src/backoff.ts
  dev/src/bulk-writer.ts
  dev/src/bundle.ts
  dev/src/convert.ts
  dev/src/document-reader.ts
  dev/src/document.ts
  dev/src/field-value.ts
  dev/src/geo-point.ts
  dev/src/index.ts
  dev/src/logger.ts
  dev/src/order.ts
  dev/src/path.ts
  dev/src/pool.ts
  dev/src/rate-limiter.ts
  dev/src/recursive-delete.ts
  dev/src/reference.ts
  dev/src/serializer.ts
  dev/src/timestamp.ts
  dev/src/transaction.ts
  dev/src/types.ts
  dev/src/util.ts
  dev/src/validate.ts
  dev/src/watch.ts
  dev/src/write-batch.ts
Labels: api: firestore, cla: yes

#1564 chore: add Warn to generated client
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  synth.metadata
  types/v1/firestore_admin_client.d.ts
  types/v1/firestore_client.d.ts
  types/v1beta1/firestore_client.d.ts
Labels: api: firestore, automerge, cla: yes, context: full, context: partial

#1572 feat: allow UnhandledPromiseRejection errors in BulkWriter if no error handler is specified
  dev/src/bulk-writer.ts
  dev/test/bulk-writer.ts
Labels: api: firestore, cla: yes
