Repository googleapis/nodejs-firestore, pull requests merged in 2021-12, with the labels that each got.

#1639 fix: save negative zero as doubleValue
  dev/src/serializer.ts
  dev/test/document.ts
Labels: cla: yes, api: firestore

#1642 chore: remove backend_type from kokoro config
  .kokoro/release/publish.cfg
Labels: cla: yes, api: firestore

#1647 docs: add @throws API comment for CRUD methods
  dev/src/bulk-writer.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/write-batch.ts
  types/firestore.d.ts
Labels: api: firestore

#1648 docs: improve documentation for merge behavior
  dev/src/bulk-writer.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/write-batch.ts
  types/firestore.d.ts
Labels: api: firestore

#1649 chore: add api_shortname and library_type to repo metadata
  .repo-metadata.json
  README.md
Labels: automerge, api: firestore
