Repository googleapis/nodejs-firestore, pull requests merged in 2021-04, with the labels that each got.

#1462 fix: omit readTime in RunQueryRequest for recursive deletes
  dev/src/index.ts
  dev/src/reference.ts
  dev/test/query.ts
  dev/test/recursive-delete.ts
Labels: api: firestore, cla: yes

#1464 fix: remove floating point rounding error in Timestamp.fromMillis()
  dev/src/timestamp.ts
  dev/test/timestamp.ts
Labels: api: firestore, cla: yes

#1468 fix: use BigInt when calculating nanos in Timestamp.fromMillis()
  dev/src/timestamp.ts
Labels: api: firestore, cla: yes

#1470 feat: add buffering layer to BulkWriter
  dev/src/bulk-writer.ts
  dev/test/bulk-writer.ts
Labels: api: firestore, cla: yes

#1475 chore: run synthtool and fix synth.py
  dev/protos/firestore_v1beta1_proto_api.d.ts
  dev/protos/firestore_v1beta1_proto_api.js
  dev/protos/google/firestore/v1/common.proto
  dev/protos/google/firestore/v1/document.proto
  dev/protos/google/firestore/v1/firestore.proto
  dev/protos/google/firestore/v1/query.proto
  dev/protos/google/firestore/v1/write.proto
  dev/protos/google/firestore/v1beta1/common.proto
  dev/protos/google/firestore/v1beta1/document.proto
  dev/protos/google/firestore/v1beta1/firestore.proto
  dev/protos/google/firestore/v1beta1/query.proto
  dev/protos/google/firestore/v1beta1/write.proto
  dev/protos/protos.json
  dev/src/v1/firestore_client_config.json
  dev/src/v1beta1/firestore_client.ts
  dev/src/v1beta1/firestore_client_config.json
  dev/src/v1beta1/gapic_metadata.json
  dev/test/gapic_firestore_v1beta1.ts
  dev/test/index.ts
  synth.py
  types/protos/firestore_v1beta1_proto_api.d.ts
  types/v1beta1/firestore_client.d.ts
Labels: api: firestore, cla: yes

#1476 chore: fix synth.py script
  synth.metadata
  synth.py
Labels: api: firestore, cla: yes

#1479 feat: use limit queries on recursiveDelete()
  dev/src/index.ts
  dev/src/recursive-delete.ts
  dev/test/query.ts
  dev/test/recursive-delete.ts
Labels: api: firestore, cla: yes

#1485 chore: master => defaultbranch
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: firestore, cla: yes, context: none

#1484 fix: type of QuerySnapshot.docChanges() should be generic
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1487 chore: fix copyright statements
  dev/protos/google/api/annotations.proto
  dev/protos/google/api/client.proto
  dev/protos/google/api/field_behavior.proto
  dev/protos/google/api/http.proto
  dev/protos/google/api/resource.proto
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: none

#1488 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: partial

#1491 chore: regenerate protos
  dev/protos/firestore_admin_v1_proto_api.d.ts
  dev/protos/firestore_admin_v1_proto_api.js
  dev/protos/firestore_v1_proto_api.d.ts
  dev/protos/firestore_v1_proto_api.js
  dev/protos/firestore_v1beta1_proto_api.d.ts
  dev/protos/firestore_v1beta1_proto_api.js
  synth.metadata
Labels: api: firestore, cla: yes, context: none
