Repository googleapis/nodejs-firestore, pull requests merged in 2021-06, with the labels that each got.

#1525 docs: hiding MIN_PENDING_OPS from global docs
  dev/src/recursive-delete.ts
Labels: api: firestore, cla: yes

#1530 chore: Report warning on `.github/workflows/ci.yaml`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#1533 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: firestore, automerge, cla: yes

#1535 fix: bulkWriter: ensure buffered batches are sent after flush
  dev/src/bulk-writer.ts
  dev/test/bulk-writer.ts
Labels: api: firestore, cla: yes

#1534 chore: create flakybot.yaml
  .github/flakybot.yaml
Labels: api: firestore, cla: yes

#1536 fix: make request optional in all cases
  dev/src/v1/firestore_admin_client.ts
  dev/src/v1/firestore_client.ts
  dev/src/v1beta1/firestore_client.ts
  synth.metadata
  types/v1/firestore_admin_client.d.ts
  types/v1/firestore_client.d.ts
  types/v1beta1/firestore_client.d.ts
Labels: api: firestore, automerge, cla: yes, context: full

#1537 build: include version in pass down variables
  .github/auto-approve.yml
  .trampolinerc
  synth.metadata
Labels: api: firestore, automerge, cla: yes, context: full

#1540 docs: improve docs for UpdateData
  dev/src/index.ts
Labels: api: firestore, cla: yes

#1539 docs: expand documentation on transactions
  dev/src/index.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1543 build(node): don't throw on deprecation in unit tests
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#1542 chore: move transaction default max retry attempts to a const
  dev/src/index.ts
Labels: api: firestore, cla: yes

#1544 feat: retry BatchGetDocuments RPCs that fail with errors
  dev/src/document-reader.ts
  dev/src/index.ts
  dev/src/transaction.ts
  dev/test/index.ts
Labels: api: firestore, cla: yes

#1541 feat: add read-only transactions
  dev/src/index.ts
  dev/src/transaction.ts
  dev/src/validate.ts
  dev/system-test/firestore.ts
  dev/test/transaction.ts
  types/firestore.d.ts
Labels: api: firestore, cla: yes

#1546 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: firestore, automerge, cla: yes

#1549 fix: lower batch size on BulkWriter retry
  dev/src/bulk-writer.ts
  dev/test/bulk-writer.ts
  dev/test/recursive-delete.ts
Labels: api: firestore, cla: yes
