Repository googleapis/nodejs-firestore, pull requests merged in 2022-09, with the labels that each got.

#1766 fix: Version 7 of protobufjs requires update.sh script to be fixed.
  dev/protos/update.sh
Labels: api: firestore, size: xs

#1769 fix: Remove hack in update.sh, and replace with existing pattern for protobuf dependencies.
  dev/protos/update.sh
Labels: api: firestore, size: xs

#1698 feat: Use REST
  dev/src/bulk-writer.ts
  dev/src/collection-group.ts
  dev/src/document-reader.ts
  dev/src/index.ts
  dev/src/pool.ts
  dev/src/recursive-delete.ts
  dev/src/reference.ts
  dev/src/util.ts
  dev/src/watch.ts
  dev/src/write-batch.ts
  dev/system-test/firestore.ts
  dev/test/index.ts
  dev/test/pool.ts
  dev/test/util/helpers.ts
  package.json
  types/firestore.d.ts
Labels: api: firestore, size: l

#1771 fix: minify proto JSON files
  package.json
Labels: api: firestore, size: xs

#1772 fix: Tests will now verify asynchronous termination of underlying steam, and fix related bug.
  dev/src/reference.ts
  dev/test/bulk-writer.ts
  dev/test/partition-query.ts
  dev/test/query.ts
  dev/test/recursive-delete.ts
  dev/test/util/helpers.ts
Labels: api: firestore, size: m

#1761 feat: Add internal multi-db support
  dev/src/index.ts
  dev/test/index.ts
  types/firestore.d.ts
Labels: api: firestore, size: m
