Repository googleapis/nodejs-firestore, pull requests merged in 2022-10, with the labels that each got.

#1783 docs: Write javadocs for COUNT API
  dev/src/reference.ts
  types/firestore.d.ts
Labels: api: firestore, size: l

#1774 feat: COUNT Queries
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/src/types.ts
  dev/system-test/firestore.ts
  dev/test/aggregateQuery.ts
  dev/test/transaction.ts
  dev/test/util/helpers.ts
  types/firestore.d.ts
Labels: api: firestore, size: l

#1728 fix: Remove @internal annotation from snapshot_
  dev/src/index.ts
Labels: api: firestore, size: xs

#1739 chore(converter): correct spelling of error message
  dev/src/convert.ts
  dev/test/index.ts
Labels: automerge, kokoro:run, api: firestore, size: xs

#1524 docs: remove wrapped region tags
  samples/solution-counters.js
Labels: cla: yes, automerge, api: firestore, size: xs
