Repository googleapis/nodejs-firestore, pull requests merged in 2024-05, with the labels that each got.

#2017 feat: Lazy-started transactions
  dev/conformance/runner.ts
  dev/src/document-reader.ts
  dev/src/index.ts
  dev/src/reference.ts
  dev/src/transaction.ts
  dev/test/aggregateQuery.ts
  dev/test/ignore-undefined.ts
  dev/test/partition-query.ts
  dev/test/query.ts
  dev/test/transaction.ts
  dev/test/util/helpers.ts
  dev/test/vector-query.ts
Labels: api: firestore, size: xl

#2039 fix: Nonblocking rollback
  dev/src/transaction.ts
Labels: api: firestore, size: s

#2040 fix: Upgrade the `google-gax` dependency version.
  package.json
Labels: api: firestore, size: xs

#2037 chore: refactor reference.ts to one class per file
  api-report/firestore.api.md
  dev/src/bundle.ts
  dev/src/collection-group.ts
  dev/src/document-reader.ts
  dev/src/document.ts
  dev/src/index.ts
  dev/src/query-partition.ts
  dev/src/recursive-delete.ts
  dev/src/reference.ts
  dev/src/reference/aggregate-query-snapshot.ts
  dev/src/reference/aggregate-query.ts
  dev/src/reference/collection-reference.ts
  dev/src/reference/composite-filter-internal.ts
  dev/src/reference/constants.ts
  dev/src/reference/document-reference.ts
  dev/src/reference/field-filter-internal.ts
  dev/src/reference/field-order.ts
  dev/src/reference/filter-internal.ts
  dev/src/reference/helpers.ts
  dev/src/reference/query-options.ts
  dev/src/reference/query-snapshot.ts
  dev/src/reference/query-util.ts
  dev/src/reference/query.ts
  dev/src/reference/types.ts
  dev/src/reference/vector-query-options.ts
  dev/src/reference/vector-query-snapshot.ts
  dev/src/reference/vector-query.ts
  dev/src/transaction.ts
  dev/src/write-batch.ts
Labels: api: firestore, size: xl

#2045 feat: Query profiling for VectorQuery
  dev/src/reference/vector-query.ts
  dev/system-test/firestore.ts
Labels: automerge, api: firestore, size: m
