Repository googleapis/nodejs-firestore, pull requests merged in 2024-01, with the labels that each got.

#1967 fix: Make transaction rollback best effort.
  dev/src/transaction.ts
  dev/test/transaction.ts
Labels: api: firestore, size: s

#1974 docs: tweak Count API docs
  dev/src/reference.ts
  types/firestore.d.ts
Labels: api: firestore, size: s

#1975 ci: Trampoline image to Node 14
  .kokoro/common.cfg
Labels: api: firestore, size: xs

#1980 ci: update trampoline image to Node 14 in docs.cfg
  .kokoro/release/docs.cfg
Labels: automerge, api: firestore, size: xs

#1986 test: update conformance tests to 3264aa6
  dev/conformance/conformance-tests/query-cursor-startafter-docsnap.json
  dev/conformance/conformance-tests/query-invalid-operator.json
  dev/conformance/conformance-tests/set-arrayunion-merge.json
Labels: api: firestore, size: m

#1983 fix: Remove incorrect,unreachable and unused code
  dev/src/index.ts
Labels: kokoro:run, api: firestore, size: xs

#1988 docs: FirestoreDataConverter doc and test improvements
  dev/test/types.ts
  types/firestore.d.ts
Labels: api: firestore, size: m

#1985 fix: Allow an explicit MustExist precondition for update
  dev/conformance/conformance-tests/update-exists-false-precond.json
  dev/conformance/conformance-tests/update-exists-true-precond.json
  dev/conformance/conformance-tests/update-paths-exists-false-precond.json
  dev/conformance/conformance-tests/update-paths-exists-true-precond.json
  dev/src/write-batch.ts
  dev/test/document.ts
Labels: api: firestore, size: m
