Repository googleapis/nodejs-firestore, pull requests merged in 2024-09, with the labels that each got.

#2090 feat: Return computed distance and set distance thresholds on VectorQueries
  api-report/firestore.api.md
  dev/src/index.ts
  dev/src/reference/query.ts
  dev/src/reference/vector-query-options.ts
  dev/src/reference/vector-query.ts
  dev/system-test/firestore.ts
  dev/test/vector-query.ts
  package.json
  types/firestore.d.ts
Labels: api: firestore, size: xl

#2187 build: fix path-to-regexp to older version due to node 14 requirement.
  package.json
Labels: api: firestore, size: xs

#2181 refactor: Add settings attributes to trace spans.
  dev/src/index.ts
  dev/src/telemetry/disabled-trace-util.ts
  dev/src/telemetry/enabled-trace-util.ts
  dev/src/telemetry/trace-util.ts
  dev/system-test/tracing.ts
Labels: api: firestore, size: m
