Repository googleapis/nodejs-firestore, pull requests merged in 2024-12, with the labels that each got.

#2218 feat: Enable tracing via OpenTelemetry.
  dev/src/index.ts
  dev/src/reference/query-util.ts
  dev/src/telemetry/disabled-trace-util.ts
  dev/src/telemetry/enabled-trace-util.ts
  dev/src/telemetry/span.ts
  dev/src/telemetry/trace-util.ts
  dev/system-test/tracing.ts
  dev/test/tracing.ts
  types/firestore.d.ts
Labels: api: firestore, size: l

#2245 test: fix flaky tracing test.
  dev/system-test/tracing.ts
Labels: api: firestore, size: s

#2199 chore: cleanup docs and tests related to vector query
  dev/src/reference/query.ts
  dev/system-test/firestore.ts
  dev/test/vector-query.ts
Labels: api: firestore, size: s

#2247 chore: deps update node 14
  package.json
Labels: api: firestore, size: xs

#2238 chore: Support `fire-admin` tag for Admin Node SDK
  dev/src/index.ts
Labels: automerge, api: firestore, size: xs

#2252 feat: Support `fire-admin` tag for Admin Node SDK
  dev/src/index.ts
Labels: automerge, api: firestore, size: xs

#2259 fix: correctly escape field paths with multiple backslashes or backticks
  dev/src/path.ts
  dev/test/path.ts
Labels: api: firestore, size: s

#2257 Fix: sort document reference by long type id
  dev/src/path.ts
  dev/system-test/firestore.ts
Labels: api: firestore, size: m

#2261 fix: correctly escape field paths with multiple backslashes or backticks (#2259)
  dev/src/path.ts
  dev/test/path.ts
Labels: api: firestore, size: s
